export const PoliticasData = [
  {
    titulo: "Política 1",
    cedula_empresa: "987654321",
    descripcion: "Esta política establece las reglas para las vacaciones en 2023.",
    periodo: 7,
    fecha_inicio: "2023-10-01",
    fecha_final: "2023-12-31",
    dias_a_dar: 15,
    inicia_desde_contrato: true,
    acumulativo: false,
    incrementativo: true,
    dias_a_incrementar: 3,
    activo: true,
  },
  {
    titulo: "Política 2",
    cedula_empresa: "987654321",
    descripcion: "Esta política otorga licencia por maternidad a empleadas embarazadas.",
    periodo: 15,
    fecha_inicio: "2023-10-01",
    fecha_final: "2023-12-31",
    dias_a_dar: 60,
    inicia_desde_contrato: false,
    acumulativo: true,
    incrementativo: true,
    dias_a_incrementar: 4,
    activo: true,
  },
  {
    titulo: "Política 3",
    cedula_empresa: "987654321",
    descripcion: "Los empleados pueden tomar hasta 5 días personales al año.",
    periodo: 7,
    fecha_inicio: "2023-10-01",
    fecha_final: "2023-12-31",
    dias_a_dar: 5,
    inicia_desde_contrato: false,
    acumulativo: true,
    incrementativo: true,
    dias_a_incrementar: 2,
    activo: true,
  },
  {
    titulo: "Política 4",
    cedula_empresa: "987654321",
    descripcion: "Esta política establece las reglas para las vacaciones en 2024.",
    periodo: 7,
    fecha_inicio: "2024-10-01",
    fecha_final: "2024-12-31",
    dias_a_dar: 15,
    inicia_desde_contrato: true,
    acumulativo: true,
    incrementativo: true,
    dias_a_incrementar: 3,
    activo: true,
  },
  {
    titulo: "Política 5",
    cedula_empresa: "987654321",
    descripcion: "Esta política otorga licencia por enfermedad a los empleados.",
    periodo: 10,
    fecha_inicio: "2023-10-01",
    fecha_final: "2023-12-31",
    dias_a_dar: 10,
    inicia_desde_contrato: false,
    acumulativo: true,
    incrementativo: true,
    dias_a_incrementar: 2,
    activo: true,
  },
  {
    titulo: "Política 6",
    cedula_empresa: "987654321",
    descripcion: "Esta política otorga licencia por enfermedad a los empleados.",
    periodo: 1,
    fecha_inicio: "2023-10-01",
    fecha_final: "2023-12-31",
    dias_a_dar: 1,
    inicia_desde_contrato: 0,
    acumulativo: 0,
    incrementativo: 0,
    dias_a_incrementar: 0,
    activo: true,
  },
];


export const LibresData = [
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 1",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 15,
    dias_libres_utilizados: 0,
    periodosRecorridos: 0,
  },
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 2",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 100,
    dias_libres_utilizados: 0,
    periodosRecorridos: 2,
  },
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 3",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 5,
    dias_libres_utilizados: 0,
    periodosRecorridos: 0,
  },
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 4",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 15,
    dias_libres_utilizados: 0,
    periodosRecorridos: 0,
  },
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 5",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 0,
    dias_libres_utilizados: 0,
    periodosRecorridos: 1,
  },
  {
    cedula_empleado: "123456789",
    titulo_politica: "Política 6",
    cedula_empresa: "987654321",
    dias_libres_disponibles: 0,
    dias_libres_utilizados: 0,
    periodosRecorridos: 0,
  },
];

